from setuptools import setup
setup(name='AquilaSV',      
version='1.5',      
description='A phased diploid assembly and SV calling tool',      
author='Xin Zhou',      
author_email='mazie.zhou@vanderbilt.edu',      
install_requires=['numpy','samtools','spades','k8'],         
license='MIT',      
packages=['bin',],
package_data={'bin' : ['paftools/*',
                     'k8-0.2.4/*',
                     'header/*',
                     'SPAdes-3.13.0-Linux/bin/*',
                     'SPAdes-3.13.0-Linux/share/spades/*',
                     'SPAdes-3.13.0-Linux/share/spades/configs/corrector/*',
                     'SPAdes-3.13.0-Linux/share/spades/configs/debruijn/*',
                     'SPAdes-3.13.0-Linux/share/spades/configs/hammer/*',
                     'SPAdes-3.13.0-Linux/share/spades/configs/ionhammer/*',
                     'SPAdes-3.13.0-Linux/share/spades/joblib3/*',
                     'SPAdes-3.13.0-Linux/share/spades/joblib2/*',
                     'SPAdes-3.13.0-Linux/share/spades/pyyaml2/*',
                     'SPAdes-3.13.0-Linux/share/spades/pyyaml3/*',
                     'SPAdes-3.13.0-Linux/share/spades/test_dataset/*',
                     'SPAdes-3.13.0-Linux/share/spades/test_dataset_plasmid/*',
                     'SPAdes-3.13.0-Linux/share/spades/test_dataset_truspades/*',
                     'SPAdes-3.13.0-Linux/share/spades/spades_pipeline/*',
                     'SPAdes-3.13.0-Linux/share/spades/spades_pipeline/common/*',
                     'SPAdes-3.13.0-Linux/share/spades/spades_pipeline/truspades/*',
                     ]},  
entry_points={'console_scripts':['AquilaSV_step1=bin.AquilaSV_step1:main',
'AquilaSV_step2=bin.AquilaSV_step2:main',
'AquilaSV_step3=bin.AquilaSV_step3:main'
               ]},
zip_safe=False)
